Add subscriptions tests
inferno-framework/davinci-pas-test-kit pull request #23
Opened 2024-12-18 19:39 UTC by karlnaden

# Summary

Replace attestations of pending request notifications / updates with actual mechanical Subscriptions interactions.

Did a very simple import of Subscriptions tests, but significant massaging is probably needed, particularly around making sure that wait tests are grouped appropriately e.g.,
- currently subscription creation and notifications are grouped, when subscription creation may happen much earlier
- on the client side, notification and $inquire may happen close together and require tighter integration than we have currently.

# Testing Guidance

TODO

2025-02-26 04:12 UTC, tstrass requested changes

2025-02-26 04:12 UTC, tstrass commented on lib/davinci_pas_test_kit/endpoints/subscription_read_endpoint.rb
This looks to be identical to the one in the subscriptions test kit. Can we just reuse it instead of duplicating in this case?

2025-02-26 04:12 UTC, tstrass commented on lib/davinci_pas_test_kit/endpoints/subscription_status_endpoint.rb
This looks to be identical to the one in the subscriptions test kit. Can we just reuse it instead of duplicating in this case?

2025-02-26 04:12 UTC, tstrass commented on lib/davinci_pas_test_kit/generator/group_generator.rb
> +              - Respond to a prior authorization request with an `pended` status.
```suggestion
              - Respond to a prior authorization request with a `pended` status.
```

2025-02-26 19:25 UTC, karlnaden commented on lib/davinci_pas_test_kit/custom_groups/v2.0.1/client_tests/pas_client_pas_inquire_request_bundle_validation_test.rb
It is no longer generated because there are not enough of them to justify the complexity of creating a generator.  I can fix the file name / class name mismatch

2025-02-26 19:52 UTC, karlnaden commented on lib/davinci_pas_test_kit/custom_groups/v2.0.1/client_tests/pas_client_subscription_pas_conformance_test.rb
> +        unless filter_criteria&.length == 1
We still send notifications based on the Subscription because we can't really evaluate whether the criteria are met or not since they aren't formally defined in R4.  So I think that 201 created is still right. I'm open to a larger discussion about whether we should be more picky about what Subscriptions we accept, but I think this is fine for this initial PR with subscriptions.

2025-02-26 20:10 UTC, karlnaden commented on config/PAS Client Test Suite Demo.postman_collection.json
> +		"oauth2": [
When you get a new token, this setting automatically resets to on. I think this has to be fixed as a part of a larger improvement to our auth simulation, which is something I'm working on.

2025-02-26 20:13 UTC, karlnaden commented on lib/davinci_pas_test_kit/docs/client_suite_description_v201.md
> +under the `_payload` element).
Correct - PAS doesn't support empty notifications. From the [spec](https://hl7.org/fhir/us/davinci-pas/STU2/specification.html#subscription):
> PAS Clients and Intermediaries SHALL support subscriptions with content=’id-only’ but MAY by mutual agreement and with appropriate security arrangements in place for push notifications containing PHI also support content=’full-resource’.

There's no mention of Empty, which I interpret to mean no support. From a practical perspective on empty, there's no way to know what Prior auth the notification is for.

2025-02-26 20:24 UTC, karlnaden commented on lib/davinci_pas_test_kit/client_suite.rb
> +    suite_endpoint :post, FHIR_SUBSCRIPTION_RESOURCE_STATUS_PATH, SubscriptionStatusEndpoint
updated to fixed version

2025-02-26 20:29 UTC, karlnaden commented on lib/davinci_pas_test_kit/client_suite.rb
> +    suite_endpoint :get, FHIR_SUBSCRIPTION_INSTANCE_STATUS_PATH, SubscriptionStatusEndpoint
Inferno needs a notification bundle to build the status. This is a bug because I haven't updated it to work when Inferno generates the notification. Working on that now.

2025-02-26 20:37 UTC, tstrass commented on lib/davinci_pas_test_kit/custom_groups/v2.0.1/client_tests/pas_client_subscription_pas_conformance_test.rb
> +        unless filter_criteria&.length == 1
Makes sense, I'm good with that

2025-02-26 20:55 UTC, karlnaden commented on lib/davinci_pas_test_kit/endpoints/claim_endpoint.rb
> +      :davinci_pas_client_suite_v201 # TODO: don't hard-code the id here...
Made an attempt to pull this information from the request object of the triggering request, which I think will be better - thanks for noticing this reminder.

2025-02-26 23:41 UTC, tstrass commented on lib/davinci_pas_test_kit/endpoints/subscription_status_endpoint.rb
@karlnaden looks like you added some logic such that it's no longer identical to the endpoint in the subscriptions test kit, meaning it has to exist separately, right?

2025-02-27 00:01 UTC, tstrass requested changes

2025-02-27 04:37 UTC, karlnaden commented on lib/davinci_pas_test_kit/endpoints/subscription_status_endpoint.rb
correct - I needed to be able to create the status even if no notification bundle was provided, so i think we keep this here. I could see a world in which we would factor the code in such a way that PAS could extend Subscriptions, but I don't think that's the right priority.

2025-02-27 14:04 UTC, tstrass approved these changes
Big improvement to the suite!

2025-02-27 14:13 UTC, merged